apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.appName }}-nginx-data"
  namespace: "{{ .Values.namespace }}"
  annotations:
    "helm.sh/hook": pre-install
data:
  index.html: |
    Home Page - Served to you from our Kubernetes Cluster
