apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.appName }}"
  name: "{{ .Values.appName }}-internal"
  namespace: "{{ .Values.namespace }}"
spec:
  ports:
  - name: "{{ .Values.appName }}"
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: "{{ .Values.appName }}"
