apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: loadbalancer
  name: loadbalancer
  namespace: "{{ .Values.namespace }}"
spec:
  host: loadbalancer-insecure.apps.ocp4.devopstower.local
  port:
    targetPort: nginx-loadbalancer
  to:
    kind: Service
    name: loadbalancer
    weight: 100
status:
  ingress: 
    - {}
