apiVersion: v1
kind: Service
metadata:
  labels:
    app: loadbalancer
  name: loadbalancer
  namespace: "{{ .Values.namespace }}"
spec:
  ports:
  - name: nginx-loadbalancer
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: loadbalancer
status:
  loadBalancer: {}
