---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: loadbalancer-payments-green
spec:
  destination:
    name: payments-green
  sources:
    - name: loadbalancer
      action: allow
