apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.appName }}"
  name: "{{ .Values.appName }}-external"
  namespace: "{{ .Values.namespace }}"
spec:
  ports:
  - name: "{{ .Values.appName }}"
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: "{{ .Values.appName }}"
  type: LoadBalancer
