apiVersion: v1
kind: Service
metadata:
  labels:
    app: consul
  name: consul-server-external
spec:
  ports:
  - name: http
    port: 8500
    protocol: TCP
    targetPort: 8500
  publishNotReadyAddresses: true
  selector:
    app: consul
    component: server
    release: consul
  type: LoadBalancer
